base:
  DOIAU: "NO"
  DO_JEDIATMVAR: "NO"
  DO_JEDIATMENS: "NO"
  DO_JEDIOCNVAR: "NO"
  DO_JEDISNOWDA: "NO"
  DO_MERGENSST: "NO"
  DO_STARTMEM_FROM_JEDIICE: "NO"
  DO_GOES: "NO"
  DO_BUFRSND: "NO"
  DO_GEMPAK: "NO"
  DO_AWIPS: "NO"
  DO_NPOESS: "NO"
  DO_TRACKER: "NO"
  DO_GENESIS: "NO"
  DO_GENESIS_FSU: "NO"
  DO_METP: "NO"
  FHMAX_GFS: 0
  FHMAX_HF_GFS: 0
  FCST_BREAKPOINTS: ""
  DO_GSISOILDA: "NO"
  DOHYBVAR_OCN: "NO"
  DOLETKF_OCN: "NO"
  DO_TEST_MODE: "NO"
  ENSREPLAY: "NO"
  DO_OMF: "YES"
  DO_POST: "NO"
  DO_FETCH_HPSS: "YES"
  DIAG_INTERVAL: 6
  RESTARTEXP: "shield2022_replay_C768b"
