#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "init" -c "base init"


##############################################
# Begin JOB SPECIFIC work
##############################################
# Ignore possible spelling error (nothing is misspelled)
# shellcheck disable=SC2153
GDATE=$(date --utc -d "${PDY} ${cyc} - ${assim_freq} hours" +%Y%m%d%H)
export GDATE

export EXTRACT_DIR=${EXTRACT_DIR:-$DATA}
if [[ $MODE = "forecast-only" && $EXP_WARM_START = ".true." ]]; then
  export EXTRACT_DIR=$ROTDIR
fi

if [[ (${ICFROM} = "gfs" && ${gfs_ver:1:2} -le 16) || (${ICFROM} != "gfs" && ${exp_ver} -lt 2024) ]]; then
  export COMIN_ATMOS_ANALYSIS=${ICSDIR}/${ICDUMP}.${PDY}/${cyc}/${COMPONENT:-"atmos"}
  export COMIN_ATMOS_ANALYSIS_RESTART=${ICSDIR}/${ICDUMP}.${PDY}/${cyc}/${COMPONENT:-"atmos"}/RESTART
else
  ROTDIR=${ICSDIR} RUN=${ICDUMP} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
         COMIN_ATMOS_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL 
  ROTDIR=${ICSDIR} RUN=${ICDUMP} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
         COMIN_ATMOS_ANALYSIS_RESTART:COM_ATMOS_RESTART_TMPL   
fi

ROTDIR=${ICSDIR}/output/${CASE} RUN=${ICDUMP} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
	COMOUT_ATMOS_INPUT:COM_ATMOS_INPUT_TMPL 
ROTDIR=${ICSDIR}/output RUN=${ICDUMP} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
        COMOUT_ATMOS_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL
ROTDIR=${ICSDIR}/output/${CASE} RUN=${ICDUMP} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
        COMOUT_ATMOS_ANALYSIS_RESTART:COM_ATMOS_RESTART_TMPL
ROTDIR=${ICSDIR}/output/${CASE_ENS} RUN=${ICDUMP} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
        COMOUT_ATMOS_ANALYSIS_RESTART_ENS:COM_ATMOS_RESTART_TMPL

###############################################################
# Run init script
###############################################################

${GLOBALINITSH:-${SCRgfs}/exglobal_init.sh}
status=$?
if [[ ${status} -ne 0 ]]; then
    exit "${status}"
fi


##############################################
# Send Alerts
##############################################
if [ ${SENDDBN} = YES -a ${RUN} = gdas ] ; then
    ${DBNROOT}/bin/dbn_alert MODEL GDAS_MSC_abias ${job} ${COMOUT_ATMOS_ANALYSIS}/${APREFIX}abias
    ${DBNROOT}/bin/dbn_alert MODEL GDAS_MSC_abias_pc ${job} ${COMOUT_ATMOS_ANALYSIS}/${APREFIX}abias_pc
    ${DBNROOT}/bin/dbn_alert MODEL GDAS_MSC_abias_air ${job} ${COMOUT_ATMOS_ANALYSIS}/${APREFIX}abias_air
fi


##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}"
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi


exit 0
