#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "init" -c "base init"


##############################################
# Set variables used in the script
##############################################
# Ignore possible spelling error (nothing is misspelled)
# shellcheck disable=SC2153
export GDATE=$(${NDATE} -"${assim_freq}" "${PDY}${cyc}")
# shellcheck disable=
export gPDY=${GDATE:0:8}
export gcyc=${GDATE:8:2}

export EXTRACT_DIR=${EXTRACT_DIR:-$DATA}
if [[ $MODE = "forecast-only" && $EXP_WARM_START = ".true." ]]; then
  export EXTRACT_DIR=$ROTDIR
fi

if [[ (${ICFROM} = "gfs" && ${gfs_ver:1:2} -le 16) || (${ICFROM} != "gfs" && ${exp_ver} -lt 2024) ]]; then
  export COMIN_ATMOS_ANALYSIS=${ICSDIR}/${ICDUMP}.${PDY}/${cyc}/${COMPONENT:-"atmos"}
  export COMIN_ATMOS_ANALYSIS_RESTART=${ICSDIR}/${ICDUMP}.${PDY}/${cyc}/${COMPONENT:-"atmos"}/RESTART
else
  ROTDIR=${ICSDIR} RUN=${ICDUMP} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
         COMIN_ATMOS_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL 
  ROTDIR=${ICSDIR} RUN=${ICDUMP} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
         COMIN_ATMOS_ANALYSIS_RESTART:COM_ATMOS_RESTART_TMPL   
fi

ROTDIR=${ICSDIR}/output/${CASE} RUN=${ICDUMP} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
	COMOUT_ATMOS_INPUT:COM_ATMOS_INPUT_TMPL 
ROTDIR=${ICSDIR}/output/${CASE} RUN=${ICDUMP} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
        COMOUT_ATMOS_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL
ROTDIR=${ICSDIR}/output/${CASE} RUN=${ICDUMP} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
        COMOUT_ATMOS_ANALYSIS_RESTART:COM_ATMOS_RESTART_TMPL
ROTDIR=${ICSDIR}/output/${CASE_ENS} RUN=${ICDUMP} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
        COMOUT_ATMOS_ANALYSIS_RESTART_ENS:COM_ATMOS_RESTART_TMPL

###############################################################
# Run init script
###############################################################

${GLOBALINITSH:-${SCRgfs}/exglobal_init.sh}
status=$?
[[ ${status} -ne 0 ]] && exit "${status}"

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi


##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || (echo "${DATAROOT} does not exist. ABORT!"; exit 1)
[[ ${KEEPDATA} = "NO" ]] && rm -rf "${DATA}"

exit 0
