#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "dfetch" -c "base dfetch"

##############################################
# Set variables used in the script
##############################################
export previous_cycle=$(${NDATE} -"${assim_freq}" "${PDY}${cyc}")
# shellcheck disable=
export gPDY=${previous_cycle:0:8}
export gcyc=${previous_cycle:8:2}

if [[ ! -d ${SAVEDIR} ]]; then mkdir -p "${SAVEDIR}"; fi

###############################################################
# Run dfetch script
###############################################################

# Calls an external bash command; do not fail on unassigned/error
set +eu
"${SCRgfs}/exglobal_dfetch.py"
export err=$?
set +x
err_chk "FATAL ERROR Failed to archive the ensemble COM structure"
set_trace
set_strict

###############################################################

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || (echo "${DATAROOT} does not exist. ABORT!"; exit 1)
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
