#! /usr/bin/env bash

source "${HOMEglobal}/ush/jjob_header.sh" -e "earc_vrfy" -c "base earc_vrfy"

##############################################
# Set variables used in the script
##############################################
# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

declare -rx COMIN_ATMOS_ANALYSIS_ENSSTAT="${ROTDIR}/${RUN}.${PDY}/${cyc}/ensstat/analysis/atmos"
declare -rx COMIN_ATMOS_HISTORY_ENSSTAT="${ROTDIR}/${RUN}.${PDY}/${cyc}/ensstat/model/atmos/history"
declare -rx COMIN_SNOW_ANALYSIS_ENSSTAT="${ROTDIR}/${RUN}.${PDY}/${cyc}/ensstat/analysis/snow"

radassim_delay=$(( assim_freq * 2 ))
SEDATE=$(date --utc +%Y%m%d%H -d "${SDATE:0:8} ${SDATE:8:2} +${radassim_delay} hours")
if [[ "${CDATE}" -le "${SEDATE}" && "${EXP_WARM_START}" = ".false." ]]; then
  export ARCHRADSTAT="NO"
else
  export ARCHRADSTAT="YES"
fi

###############################################################
# Run archive script
###############################################################

"${SCRglobal}/exglobal_enkf_earc_vrfy.py"
err=$?
if [[ ${err} -ne 0 ]]; then
    exit "${err}"
fi

###############################################################

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || (
    echo "${DATAROOT} does not exist. ABORT!"
    exit 1
)
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
