#! /usr/bin/env bash

source "${HOMEglobal}/ush/preamble.sh"
source "${HOMEglobal}/ush/jjob_header.sh" -e "getic" -c "base getic"


##############################################
# Set variables used in the script
##############################################
# Ignore possible spelling error (nothing is misspelled)
# shellcheck disable=SC2153
export CDATE=${PDY}${cyc}
export GDATE=$(date --utc -d "${PDY} ${cyc} - ${assim_freq} hours" +%Y%m%d%H)
# shellcheck disable=
export gPDY=${GDATE:0:8}
export gcyc=${GDATE:8:2}

export EXTRACT_DIR=${EXTRACT_DIR:-$ICSROOT}
if [[ $MODE = "forecast-only" || $EXP_WARM_START = ".true." ]]; then
  export EXTRACT_DIR=$ROTDIR
fi

if [[ (${ICFROM} = "gfs" && ${gfs_ver:1:2} -le 16) || (${ICFROM} != "gfs" && ${exp_ver} -lt 2024) ]]; then
  declare -rx  COMIN_ATMOS_RESTART="${EXTRACT_DIR}/${RUN}.${gPDY}/${gcyc}/atmos"
  declare -rx  COMIN_ATMOS_ANALYSIS="${EXTRACT_DIR}/${ICDUMP}.${PDY}/${cyc}/atmos"
  declare -rx  COMIN_ATMOS_ANALYSIS_RESTART="${EXTRACT_DIR}/${RUN}.${PDY}/${cyc}/atmos/RESTART"
  declare -rx  COMIN_ATMOS_ANALYSIS_PREV="${EXTRACT_DIR}/${ICDUMP}.${gPDY}/${gcyc}/atmos"
else
  declare -rx  COMIN_ATMOS_RESTART="${ROTDIR}/${RUN}.${gPDY}/${gcyc}/model/atmos/restart"
  declare -rx  COMIN_ATMOS_ANALYSIS="${ICSROOT}/output/${ICDUMP}.${PDY}/${cyc}/analysis/atmos"
  declare -rx  COMIN_ATMOS_ANALYSIS_RESTART="${ICSROOT}/${RUN}.${PDY}/${cyc}/model/atmos/restart"
  declare -rx  COMIN_ATMOS_ANALYSIS_PREV="${ICSROOT}/output/${ICDUMP}.${gPDY}/${gcyc}/analysis/atmos"
fi
export ATMOS_ANALYSIS=${COMIN_ATMOS_ANALYSIS#${EXTRACT_DIR}}
export ATMOS_ANALYSIS_RESTART=${COMIN_ATMOS_ANALYSIS_RESTART#${EXTRACT_DIR}}

declare -rx  COMOUT_ATMOS_ANALYSIS="${ICSROOT}/output/${ICDUMP}.${PDY}/${cyc}/analysis/atmos"
declare -rx  COMOUT_ATMOS_ANALYSIS_PREV="${ICSROOT}/output/${ICDUMP}.${gPDY}/${gcyc}/analysis/atmos"
declare -rx  COMOUT_ATMOS_ANALYSIS_RESTART="${ICSROOT}/${RUN}.${PDY}/${cyc}/model/atmos/restart"

declare -rx  COM_ATMOS_HISTORY_PREV="${ROTDIR}/${RUN}.${gPDY}/${gcyc}/model/atmos/history"
declare -rx  COM_ATMOS_HISTORY="${ROTDIR}/${RUN}..${PDY}/${cyc}/model/atmos/history"

###############################################################
# Run getic script
###############################################################

${GLOBALGETICSH:-${SCRglobal}/exglobal_getic.sh}
status=$?
[[ ${status} -ne 0 ]] && exit "${status}"

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi


##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || (echo "${DATAROOT} does not exist. ABORT!"; exit 1)
[[ ${KEEPDATA} = "NO" ]] && rm -rf "${DATA}"

exit 0
