#! /usr/bin/env bash

if (( 10#${ENSMEM:-0} > 0 )); then
  source "${HOMEglobal}/ush/jjob_header.sh" -e "upp" -c "base eupp"
else
  source "${HOMEglobal}/ush/jjob_header.sh" -e "upp" -c "base upp"
fi

##############################################
# Set variables used in the exglobal script
##############################################
# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

##############################################
# Begin JOB SPECIFIC work
##############################################

# Construct COM variables from templates
if (( 10#${ENSMEM:-0} > 0 )); then
  MEMDIR=${MEMDIR} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
     COMIN_ATMOS_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL \
     COMIN_ATMOS_HISTORY:COM_ATMOS_HISTORY_TMPL \
     COMOUT_ATMOS_MASTER:COM_ATMOS_MASTER_TMPL
else
  declare -rx COMIN_ATMOS_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/atmos"
  declare -rx COMIN_ATMOS_HISTORY="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/atmos/history"
  declare -rx COMOUT_ATMOS_MASTER="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/atmos/master"
fi
mkdir -p "${COMOUT_ATMOS_MASTER}"

###############################################################
# Run relevant exglobal script

"${SCRglobal}/exglobal_atmos_upp.py" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || exit 1
if [[ "${KEEPDATA:-NO}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
