#! /usr/bin/env bash

source "${HOMEglobal}/ush/jjob_header.sh" -e "init" -c "base init"


##############################################
# Begin JOB SPECIFIC work
##############################################
# Ignore possible spelling error (nothing is misspelled)
# shellcheck disable=SC2153
GDATE=$(date --utc -d "${PDY} ${cyc} - ${assim_freq} hours" +%Y%m%d%H)
export GDATE

export EXTRACT_DIR=${EXTRACT_DIR:-$DATA}
if [[ $MODE = "forecast-only" && $EXP_WARM_START = ".true." ]]; then
  export EXTRACT_DIR=$ROTDIR
fi

if [[ (${ICFROM} = "gfs" && ${gfs_ver:1:2} -le 16) || (${ICFROM} != "gfs" && ${exp_ver} -lt 2024) ]]; then
  declare -rx COMIN_ATMOS_ANALYSIS="${ICSROOT}/${ICDUMP}.${PDY}/${cyc}/atmos"
  declare -rx COMIN_ATMOS_ANALYSIS_RESTART="${ICSROOT}/${ICDUMP}.${PDY}/${cyc}/atmos/RESTART"
else
  declare -rx COMIN_ATMOS_ANALYSIS="${ICSROOT}/${ICDUMP}.${PDY}/${cyc}/analysis/atmos"
  declare -rx COMIN_ATMOS_ANALYSIS_RESTART="${ICSROOT}/${ICDUMP}.${PDY}/${cyc}/analysis/atmos/RESTART"
fi
declare -rx COMOUT_ATMOS_INPUT="${ICSROOT}/output/${CASE}/${ICDUMP}.${PDY}/${cyc}/model/atmos/input"
declare -rx COMOUT_ATMOS_ANALYSIS="${ICSROOT}/output/${ICDUMP}.${PDY}/${cyc}/analysis/atmos"
declare -rx COMOUT_ATMOS_ANALYSIS_RESTART="${ICSROOT}/output/${CASE}/${ICDUMP}.${PDY}/${cyc}/model/atmos/restart"
declare -rx COMOUT_ATMOS_ANALYSIS_RESTART_ENS="${ICSROOT}/output/${CASE_ENS}/${ICDUMP}.${PDY}/${cyc}/model/atmos/restart"

###############################################################
# Run init script
###############################################################

${GLOBALINITSH:-${SCRglobal}/exglobal_init.sh}
status=$?
if [[ ${status} -ne 0 ]]; then
    exit "${status}"
fi


##############################################
# Send Alerts
##############################################
if [ ${SENDDBN} = YES -a ${RUN} = gdas ] ; then
    ${DBNROOT}/bin/dbn_alert MODEL GDAS_MSC_abias ${job} ${COMOUT_ATMOS_ANALYSIS}/${APREFIX}abias
    ${DBNROOT}/bin/dbn_alert MODEL GDAS_MSC_abias_pc ${job} ${COMOUT_ATMOS_ANALYSIS}/${APREFIX}abias_pc
    ${DBNROOT}/bin/dbn_alert MODEL GDAS_MSC_abias_air ${job} ${COMOUT_ATMOS_ANALYSIS}/${APREFIX}abias_air
fi


##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}"
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi


exit 0
